Repository weekFlex/Cartier, pull requests merged in 2021-07, with the labels that each got.

#28 [Network] Moya 서버 셋팅 및 예시 서버 연결
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Model/GenericResponse.swift
  WeekFlex/WeekFlex/Global/Model/SimpleResponse.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Global/Service/NetworkResult.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/AllTaskCollectionViewCellViewModel.swift
Labels: :hand: 도와주세요, :pencil2: MVVM 적용, 🍎 민희

#29 [network] 루틴 만들기 - 카테고리 서버 연결
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Model/CategoryData.swift
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/CategoryCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
Labels: :electric_plug: 서버API, 🍎 민희

#30 [style] Home화면 collection View 수정
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/MainHome/Storyboard/MainHome.storyboard
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
Labels: :apple: 혜린, :art: 레이아웃, :checkered_flag: 완료!

#33 [network][style] 루틴 만들기 서버 연결 후 custom layout 적용
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/CategoryCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/LeftAlignFlowLayout.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-24-star-n0.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-24-star-n0.imageset/icon24StarDisabled.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-24-star-n0.imageset/icon24StarDisabled@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-24-star-n0.imageset/icon24StarDisabled@3x.png
Labels: :+1: 개선해보았어요, :art: 레이아웃, :electric_plug: 서버API, 🍎 민희, 🪄기능제작

#34 [style] 루틴 최종 점검 View Layout
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Extension/UIButton+Extension.swift
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/CheckRoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/SelectedRoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/CheckRoutineVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/AllTaskCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/CategoryCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/SelectedCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/ToDoListCollectionViewCellViewModel.swift
Labels: :art: 레이아웃, :checkered_flag: 완료!, 🍎 민희

#35 [api] 내 루틴 api 연결 완료
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Model/RoutineData.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/MyRoutine/Cell/MyRoutineListItemTableViewCell.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/Service/RoutineService.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineAddVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewModel/MyRoutineListViewModel.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewModel/RoutineListViewModel.swift
Labels: :apple: 민승, :checkered_flag: 완료!, :electric_plug: 서버API, :pencil2: MVVM 적용

#36 [feat] 루틴 수정하기 뷰 재사용 후 연결
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex/Global/Model/RoutineData.swift
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/CheckRoutineVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/Storyboard/MyRoutine.storyboard
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewModel/RoutineListViewModel.swift
Labels: :checkered_flag: 완료!, :confetti_ball: 뷰 연결, 🍎 민희

#37 [feat] 중복 루틴 이름 검사
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewModel/RoutineListViewModel.swift
Labels: :checkered_flag: 완료!, 🍎 민희, 🪄기능제작

#38 [feat ]EditRoutineVC & SelectToDo connect 완료!
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Global/Protocol/SaveTimeProtocol.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Model/ToDo.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Storyboard/EditRoutine.storyboard
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineTimeVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewModel/EditRoutineVM.swift
Labels: :+1: 개선해보았어요, :apple: 민승, :art: 레이아웃, :checkered_flag: 완료!, :confetti_ball: 뷰 연결, :pencil2: MVVM 적용, 🪄기능제작

#40 [feat] MainHome 서버 연결
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex.xcodeproj/xcshareddata/xcschemes/WeekFlex.xcscheme
  WeekFlex/WeekFlex/Global/Model/DailyData.swift
  WeekFlex/WeekFlex/Global/Model/SimpleData.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/MainHome/Cell/CalendarCell.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TableViewCell.xib
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TaskListView.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TaskListView.xib
  WeekFlex/WeekFlex/Screen/MainHome/Storyboard/MainHome.storyboard
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/EditPopUpVC.swift
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
  WeekFlex/WeekFlex/Screen/Review/Cell/ReviewCell.xib
Labels: :apple: 혜린, :art: 레이아웃, :checkered_flag: 완료!, :electric_plug: 서버API

#41 [feat] 월~일 순서대로 처리, 요일 안누르면 체크 버튼 비활성화 처리, view category VC 연결 완료!
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Protocol/Protocol.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Cell/CategoryTableViewCell.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Cell/ColorCategoryTableViewCell.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Model/CategoryDataWithoutID.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Service/CategoryService.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Storyboard/EditRoutine.storyboard
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/CreateCategoryVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/ViewCategoryVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewModel/CategoryVM.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewModel/EditRoutineVM.swift
  WeekFlex/WeekFlex/Screen/MainHome/Storyboard/MainHome.storyboard
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24CheckVisualWhite.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24CheckVisualWhite.imageset/icon24CheckVisualWhite.pdf
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32PlusBasic.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32PlusBasic.imageset/icon32PlusBasic.pdf
Labels: :+1: 개선해보았어요, :apple: 민승, :checkered_flag: 완료!

#46 [style] 루틴 생성 - task 선택 후 시간 설정 시 label에 시간 띄우기
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Extension/UIString+Extension.swift
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/CheckRoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/CheckRoutineVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineVC.swift
Labels: :art: 레이아웃, :checkered_flag: 완료!, 🍎 민희, 🪄기능제작

#47 Main home/network
  WeekFlex/WeekFlex/Global/Model/DailyData.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewModel/EditRoutineVM.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/CalendarCell.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TaskListView.swift
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/EditPopUpVC.swift
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
Labels: :apple: 혜린, :art: 레이아웃, :bug: 버그발견, :checkered_flag: 완료!, :electric_plug: 서버API

#48 [feat, layout, api] 홈 뷰에서 할일 추가, 수정, 루틴가져오기 모두 연결 완료
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Extension/UIColor+Extension.swift
  WeekFlex/WeekFlex/Global/Model/CreateTodoResponseData.swift
  WeekFlex/WeekFlex/Global/Model/DailyData.swift
  WeekFlex/WeekFlex/Global/Model/SimpleData.swift
  WeekFlex/WeekFlex/Global/Protocol/Protocol.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Service/TodoService.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/Storyboard/EditRoutine.storyboard
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/CreateCategoryVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/ViewCategoryVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewModel/CategoryVM.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewModel/EditRoutineVM.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TaskListView.swift
  WeekFlex/WeekFlex/Screen/MainHome/Storyboard/MainHome.storyboard
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/Storyboard/MyRoutine.storyboard
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewModel/RoutineListViewModel.swift
Labels: :+1: 개선해보았어요, :apple: 민승, :art: 레이아웃, :checkered_flag: 완료!, :confetti_ball: 뷰 연결, :pencil2: MVVM 적용

#49 [refac] 네브바 연결 완료!
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineVC.swift
  WeekFlex/WeekFlex/Screen/MainHome/Storyboard/MainHome.storyboard
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
Labels: :+1: 개선해보았어요, :apple: 민승, :art: 레이아웃, :checkered_flag: 완료!

#50 [network][style] 루틴 만들기 서버 연결 및 버튼 생성
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Extension/UIString+Extension.swift
  WeekFlex/WeekFlex/Global/Model/MakeRoutineData.swift
  WeekFlex/WeekFlex/Global/Model/TaskData.swift
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Global/Service/APITarget.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/CheckRoutineVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/EditRoutine/ViewController/EditRoutineVC.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32Plus.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32Plus.imageset/icon32Plus.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32Plus.imageset/icon32Plus@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32Plus.imageset/icon32Plus@3x.png
Labels: :art: 레이아웃, :checkered_flag: 완료!, :confetti_ball: 뷰 연결, :electric_plug: 서버API, 🍎 민희

#51 [network][style] 메인 홈 오류 해결
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Global/Service/APIService.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/CalendarCell.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TaskListView.swift
  WeekFlex/WeekFlex/Screen/MainHome/Cell/TaskListView.xib
  WeekFlex/WeekFlex/Screen/MainHome/Storyboard/MainHome.storyboard
  WeekFlex/WeekFlex/Screen/MainHome/ViewController/MainHomeVC.swift
  WeekFlex/WeekFlex/Screen/Tabbar/TabBar.storyboard
  WeekFlex/WeekFlex/Screen/Tabbar/TabBarVC.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-home-active.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-home-active.imageset/icon-32-home-active.svg
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-home-disable.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-home-disable.imageset/icon-32-home-disable.svg
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-myPage-active.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-myPage-active.imageset/icon-32-myPage-active.svg
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-myPage-disable.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-myPage-disable.imageset/icon-32-myPage-disable.svg
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-review-active.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-review-active.imageset/icon-32-review-active.svg
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-review-disable.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon-32-review-disable.imageset/icon-32-review-disable.svg
Labels: :apple: 혜린, :art: 레이아웃
