Repository weekFlex/Cartier, pull requests merged in 2021-03, with the labels that each got.

#6 [network] sign in with apple 기능 추가
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/Login/Storyboard/Login.storyboard
  WeekFlex/WeekFlex/Screen/Login/ViewController/LoginVC.swift
  WeekFlex/WeekFlex/Support/Delegate/AppDelegate.swift
  WeekFlex/WeekFlex/WeekFlex.entitlements
Labels: :apple: 민승, :checkered_flag: 완료!, :electric_plug: 서버API

#9 [style] 나의 루틴 뷰 레이아웃 완료
  WeekFlex/Podfile
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex.xcworkspace/contents.xcworkspacedata
  WeekFlex/WeekFlex.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  WeekFlex/WeekFlex/Global/Extension/UIColor+Extension.swift
  WeekFlex/WeekFlex/Global/Extension/UIFont+Extension.swift
  WeekFlex/WeekFlex/Global/Extension/UILabel+Extension.swift
  WeekFlex/WeekFlex/Global/Extension/UIView+Extension.swift
  WeekFlex/WeekFlex/Info.plist
  WeekFlex/WeekFlex/Screen/MyRoutine/Cell/MyRoutineListItemTableViewCell.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/Storyboard/MyRoutine.storyboard
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineAddVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewController/MyRoutineListVC.swift
  WeekFlex/WeekFlex/Screen/MyRoutine/ViewModel/MyRoutineListViewModel.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24PlusVisual.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24PlusVisual.imageset/icon24PlusVisual.pdf
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24StarN1.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24StarN1.imageset/icon24StarN1.pdf
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24StarN3.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24StarN3.imageset/icon24StarN3.pdf
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24StarN8.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon24StarN8.imageset/icon24StarN8.pdf
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32BackBlack.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32BackBlack.imageset/icon32BackBlack.pdf
  WeekFlex/WeekFlex/Support/Font/Metropolis-Black.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-BlackItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-Bold.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-BoldItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-ExtraBold.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-ExtraBoldItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-ExtraLight.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-ExtraLightItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-Light.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-LightItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-Medium.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-MediumItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-Regular.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-RegularItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-SemiBold.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-SemiBoldItalic.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-Thin.otf
  WeekFlex/WeekFlex/Support/Font/Metropolis-ThinItalic.otf
Labels: :apple: 민승, :art: 레이아웃, :checkered_flag: 완료!, :pencil2: MVVM 적용

#12 [style] 할 일 리스트 View Layout
  WeekFlex/Podfile.lock
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex.xcodeproj/xcshareddata/xcschemes/WeekFlex.xcscheme
  WeekFlex/WeekFlex/Screen/todoList/Cell/CategoryCell.swift
  WeekFlex/WeekFlex/Screen/todoList/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/todoList/Cell/SelectedRoutineCell.swift
  WeekFlex/WeekFlex/Screen/todoList/Storyboard/ToDoList.storyboard
  WeekFlex/WeekFlex/Screen/todoList/ViewController/ToDoListVC.swift
  WeekFlex/WeekFlex/Screen/todoList/ViewModel/CategoryCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/todoList/ViewModel/SelectedCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/todoList/ViewModel/ToDoListCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon12StarN3.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon12StarN3.imageset/icon12StarN3.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon12StarN3.imageset/icon12StarN3@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon12StarN3.imageset/icon12StarN3@3x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkActive.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkActive.imageset/icon16BookmarkActive.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkActive.imageset/icon16BookmarkActive@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkActive.imageset/icon16BookmarkActive@3x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkInactive.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkInactive.imageset/icon16BookmarkInactive.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkInactive.imageset/icon16BookmarkInactive@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16BookmarkInactive.imageset/icon16BookmarkInactive@3x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16CancleBlack.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16CancleBlack.imageset/icon16CancleBlack.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16CancleBlack.imageset/icon16CancleBlack@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16CancleBlack.imageset/icon16CancleBlack@3x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16SearchInactive.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16SearchInactive.imageset/icon16SearchInactive.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16SearchInactive.imageset/icon16SearchInactive@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon16SearchInactive.imageset/icon16SearchInactive@3x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32BackWhite.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32BackWhite.imageset/icon32BackWhite.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32BackWhite.imageset/icon32BackWhite@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32BackWhite.imageset/icon32BackWhite@3x.png
Labels: :art: 레이아웃, :checkered_flag: 완료!, :pencil2: MVVM 적용, 🍎 민희

#14 [sytle] 루틴 추가 - 이름 입력하기 뷰 Layout 잡기
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/CategoryCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/RoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Cell/SelectedRoutineCell.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectRoutineVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/CategoryCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/SelectedCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/ToDoListCollectionViewCellViewModel.swift
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckBlack.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckBlack.imageset/icon32CheckBlack.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckBlack.imageset/icon32CheckBlack@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckBlack.imageset/icon32CheckBlack@3x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckInactive.imageset/Contents.json
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckInactive.imageset/icon32CheckInactive.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckInactive.imageset/icon32CheckInactive@2x.png
  WeekFlex/WeekFlex/Support/Assets.xcassets/icon32CheckInactive.imageset/icon32CheckInactive@3x.png
Labels: :art: 레이아웃, :checkered_flag: 완료!, 🍎 민희

#16 [feat] 루틴 추가 뷰 연결하기
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectRoutineVC.swift
Labels: :checkered_flag: 완료!, :confetti_ball: 뷰 연결, 🍎 민희

#18 [feat] 할 일 추가 뷰 - 전체 카테고리 추가
  WeekFlex/WeekFlex.xcodeproj/project.pbxproj
  WeekFlex/WeekFlex/Screen/AddRoutine/Storyboard/AddRoutine.storyboard
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/MakeRoutineNameVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewController/SelectToDoVC.swift
  WeekFlex/WeekFlex/Screen/AddRoutine/ViewModel/CategoryCollectionViewCellViewModel.swift
Labels: :checkered_flag: 완료!, 🍎 민희, 🪄기능제작
